---
- name: Install UFW
  apt: name=ufw state=present

- name: Configure ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  notify: restart ufw

- name: Open SOCKS5 and SSH ports
  ufw:
    port: "{{ item }}"
    proto: tcp
    rule: allow
  with_items:
    - ssh
    - "{{ tport }}"
  notify: restart ufw

- name: Open UDP ports
  ufw:
    port: 40000:45000
    proto: udp
    rule: allow
  notify: restart ufw

- name: Tinyproxy 443
  ufw:
    port: 443
    proto: tcp
    rule: allow
  notify: restart ufw

- name: Tinyproxy 563
  ufw:
    port: 563
    proto: tcp
    rule: allow
  notify: restart ufw

- name: Open SQUID ports
  ufw:
    port: 3128
    proto: tcp
    rule: allow
  notify: restart ufw

- name: Enable ufw logging
  ufw: logging=on
  notify: restart ufw

- name: Enable ufw
  ufw: state=enabled
